name: Test and Build Rust

on:
  push:
  pull_request:
    types: [opened, reopened]
  schedule:
    # Check if it works with current dependencies (weekly on Wednesday 2:32 UTC)
    - cron: '32 2 * * 3'


jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v4


      - name: Setup Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}


      - name: Run clippy
        run: cargo clippy --verbose --all-targets --all-features -- -D warnings

  test_postgres_blocking:
    name: Test blocking
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        # Set health checks to wait until postgres has started

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Install diesel-cli
        run: cargo install diesel_cli --no-default-features --features postgres

      - name: Setup Postgres db
        working-directory: ./migrations
        run: diesel setup --database-url "postgres://postgres:postgres@localhost/meme_bot"

      - name: Run tests
        run: cargo test

  release:
    name: Release x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build release
        run: cargo build --release --verbose --all-features --target x86_64-unknown-linux-gnu
